package org.rajorgunit.rajsample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class sampleObj1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public sampleObj1() {
    }

}