package org.rajorgunit.rajsample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class sampleObj1 implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String field1;
   private java.lang.Boolean field2;

   public sampleObj1()
   {
   }

   public java.lang.String getField1()
   {
      return this.field1;
   }

   public void setField1(java.lang.String field1)
   {
      this.field1 = field1;
   }

   public java.lang.Boolean getField2()
   {
      return this.field2;
   }

   public void setField2(java.lang.Boolean field2)
   {
      this.field2 = field2;
   }

   public sampleObj1(java.lang.String field1, java.lang.Boolean field2)
   {
      this.field1 = field1;
      this.field2 = field2;
   }

}